import {db} from '@/db';
import {businesses,customers,orders,payments,servicePlans,subscriptions,auditLogs} from '@/db/schema';
import {and,eq} from 'drizzle-orm';
import {computeActivation} from './subscriptions';
async function businessId(){const [b]=await db.select({id:businesses.id}).from(businesses).limit(1);if(!b)throw new Error('Entreprise non initialisée');return b.id;}
export async function createCustomer(input:{firstName?:string;lastName?:string;phone:string;email?:string}){const bid=await businessId();const [row]=await db.insert(customers).values({businessId:bid,firstName:input.firstName,lastName:input.lastName,phone:input.phone,email:input.email,status:'lead'}).returning();return row;}
export async function createOrder(input:{customerId:string;total:string}){const bid=await businessId();const [row]=await db.insert(orders).values({businessId:bid,customerId:input.customerId,total:input.total,status:'new'}).returning();return row;}
export async function recordPayment(input:{customerId:string;orderId?:string;amount:string;method?:string;reference?:string}){const [row]=await db.insert(payments).values({...input,status:'submitted',paidAt:new Date()}).returning();return row;}
export async function activateSubscription(input:{subscriptionId:string}){const [s]=await db.select({id:subscriptions.id,planId:subscriptions.servicePlanId,status:subscriptions.status}).from(subscriptions).where(eq(subscriptions.id,input.subscriptionId)).limit(1);if(!s)throw new Error('Abonnement introuvable');const [plan]=await db.select({durationDays:servicePlans.durationDays,lifetime:servicePlans.lifetime}).from(servicePlans).where(eq(servicePlans.id,s.planId)).limit(1);if(!plan)throw new Error('Formule introuvable');const activation=computeActivation(plan);const [updated]=await db.update(subscriptions).set({...activation,updatedAt:new Date()}).where(and(eq(subscriptions.id,s.id),eq(subscriptions.status,'pending'))).returning();if(!updated)throw new Error('Abonnement déjà traité ou non activable');const bid=await businessId();await db.insert(auditLogs).values({businessId:bid,actorType:'admin',action:'subscription.activated',entityType:'subscription',entityId:s.id,metadata:{expiresAt:activation.expiresAt?.toISOString()??null}});return updated;}
