import {db} from '@/db';
import {businesses,customers,orders,payments,servicePlans,subscriptions,auditLogs,scheduledJobs} from '@/db/schema';
import {and,eq} from 'drizzle-orm';
import {computeActivation} from './subscriptions';
async function businessId(){const [b]=await db.select({id:businesses.id}).from(businesses).limit(1);if(!b)throw new Error('Entreprise non initialisée');return b.id;}
export async function createCustomer(input:{firstName?:string;lastName?:string;phone:string;email?:string}){const bid=await businessId();const [row]=await db.insert(customers).values({businessId:bid,firstName:input.firstName,lastName:input.lastName,phone:input.phone,email:input.email,status:'lead'}).returning();return row;}
export async function createOrder(input:{customerId:string;total:string}){const bid=await businessId();const [row]=await db.insert(orders).values({businessId:bid,customerId:input.customerId,total:input.total,status:'new'}).returning();return row;}
export async function recordPayment(input:{customerId:string;orderId?:string;amount:string;method?:string;reference?:string}){const [row]=await db.insert(payments).values({...input,status:'submitted',paidAt:new Date()}).returning();return row;}
export async function verifyPayment(input:{paymentId:string;servicePlanId:string}){const [p]=await db.select().from(payments).where(eq(payments.id,input.paymentId)).limit(1);if(!p)throw new Error('Paiement introuvable');if(p.status!=='submitted'&&p.status!=='pending')throw new Error('Paiement déjà traité');const now=new Date();const [verified]=await db.update(payments).set({status:'verified',verifiedAt:now,updatedAt:now}).where(eq(payments.id,p.id)).returning();if(p.orderId)await db.update(orders).set({status:'paid',updatedAt:now}).where(eq(orders.id,p.orderId));const [sub]=await db.insert(subscriptions).values({customerId:p.customerId,servicePlanId:input.servicePlanId,orderId:p.orderId,status:'pending'}).returning();const bid=await businessId();await db.insert(auditLogs).values({businessId:bid,actorType:'admin',action:'payment.verified',entityType:'payment',entityId:p.id,metadata:{subscriptionId:sub.id}});return{payment:verified,subscription:sub};}
async function scheduleLifecycle(subscriptionId:string,startedAt:Date,expiresAt:Date|null){const bid=await businessId();const jobs:{businessId:string;subscriptionId:string;jobType:string;runAt:Date;idempotencyKey:string;payload:Record<string,unknown>}[]=[];const add=(type:string,runAt:Date)=>jobs.push({businessId:bid,subscriptionId,jobType:type,runAt,idempotencyKey:`${subscriptionId}:${type}:${runAt.toISOString()}`,payload:{subscriptionId}});
const satisfaction=new Date(startedAt);satisfaction.setUTCDate(satisfaction.getUTCDate()+2);add('satisfaction_j2',satisfaction);
if(expiresAt)for(const days of [7,3,1]){const runAt=new Date(expiresAt);runAt.setUTCDate(runAt.getUTCDate()-days);if(runAt>startedAt)add(`expiration_j${days}`,runAt);}
if(jobs.length)await db.insert(scheduledJobs).values(jobs).onConflictDoNothing({target:scheduledJobs.idempotencyKey});}
export async function activateSubscription(input:{subscriptionId:string}){const [s]=await db.select({id:subscriptions.id,planId:subscriptions.servicePlanId,status:subscriptions.status}).from(subscriptions).where(eq(subscriptions.id,input.subscriptionId)).limit(1);if(!s)throw new Error('Abonnement introuvable');const [plan]=await db.select({durationDays:servicePlans.durationDays,lifetime:servicePlans.lifetime}).from(servicePlans).where(eq(servicePlans.id,s.planId)).limit(1);if(!plan)throw new Error('Formule introuvable');const activation=computeActivation(plan);const [updated]=await db.update(subscriptions).set({...activation,updatedAt:new Date()}).where(and(eq(subscriptions.id,s.id),eq(subscriptions.status,'pending'))).returning();if(!updated)throw new Error('Abonnement déjà traité ou non activable');await scheduleLifecycle(updated.id,updated.startedAt!,updated.expiresAt);const bid=await businessId();await db.insert(auditLogs).values({businessId:bid,actorType:'admin',action:'subscription.activated',entityType:'subscription',entityId:s.id,metadata:{expiresAt:activation.expiresAt?.toISOString()??null}});return updated;}
