import {createMemoryAction,toggleMemoryAction} from '@/app/actions/memoire';
import {listCustomers} from '@/lib/admin-data';
import {listMemoryEntries,memoryStats} from '@/lib/commercial-memory';
export const dynamic='force-dynamic';

const label=(kind:string)=>({style:'Style de réponse',knowledge:'Connaissance',policy:'Règle métier',customer_note:'Note client'} as Record<string,string>)[kind]||kind;

export default async function MemoirePage(){
 const [rows,stats,clients]=await Promise.all([listMemoryEntries(),memoryStats(),listCustomers()]);
 return <><div className="top"><div><h1>Mémoire commerciale</h1><div className="muted">Exemples de ton style, connaissances métier et notes clients utilisées comme contexte par l’IA.</div></div><strong>{stats.active} actifs</strong></div>
 <section className="grid">{[['Style',stats.style],['Connaissances',stats.knowledge],['Notes clients',stats.customerNotes],['Total',stats.total]].map(([l,v])=><div className="card" key={l}><div className="muted">{l}</div><div className="value">{v}</div></div>)}</section>
 <section className="cols"><form className="card" action={createMemoryAction}><h2>Ajouter une mémoire</h2><label>Type *</label><select name="kind" required defaultValue="style"><option value="style">Style de réponse</option><option value="knowledge">Connaissance métier</option><option value="policy">Règle métier</option><option value="customer_note">Note liée à un client</option></select><label>Titre</label><input name="title" placeholder="Ex. Réponse courte pour demander le prix"/><label>Langue</label><select name="language" defaultValue="fr"><option value="fr">Français</option><option value="en">Anglais</option></select><label>Client (seulement pour une note client)</label><select name="customerId" defaultValue=""><option value="">Aucun / global</option>{clients.map(c=><option key={c.id} value={c.id}>{[c.firstName,c.lastName].filter(Boolean).join(' ')||c.phone} — {c.phone}</option>)}</select><label>Contenu *</label><textarea name="content" rows={6} required placeholder="Colle ici un bon exemple de réponse, une règle commerciale ou une information utile."/><button type="submit">Enregistrer dans la mémoire</button></form>
 <div className="card"><h2>Comment l’IA l’utilise</h2><p>L’IA consulte les derniers messages du client, ses abonnements, les exemples de ton style et les connaissances pertinentes avant de répondre.</p><p className="muted">Les prix et disponibilités restent toujours lus depuis le catalogue actif. Une mémoire ne peut pas remplacer le catalogue comme source de vérité.</p><div className="notice">Les nouvelles conversations WhatsApp sont déjà conservées dans le CRM. L’import des anciens chats sera ajouté ensuite pour enrichir automatiquement le style.</div></div></section>
 <div className="card" style={{marginTop:16}}><h2>Mémoires enregistrées</h2>{rows.length===0?<p className="muted">Aucune mémoire enregistrée pour le moment.</p>:rows.map(r=><div className="row" key={r.id}><span><strong>{r.title||label(r.kind)}</strong><br/><span className="muted">{label(r.kind)}{r.customerId?` · ${[r.firstName,r.lastName].filter(Boolean).join(' ')||r.phone}`:' · Global'}</span><br/><span>{r.content.length>180?`${r.content.slice(0,180)}…`:r.content}</span></span><form action={toggleMemoryAction}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="active" value={String(!r.active)}/><button type="submit" className="secondary-button">{r.active?'Désactiver':'Activer'}</button></form></div>)}</div></>;
}
