import {createMemoryAction,importWhatsAppHistoryAction,toggleMemoryAction} from '@/app/actions/memoire';
import {listCustomers} from '@/lib/admin-data';
import {listMemoryEntries,memoryStats} from '@/lib/commercial-memory';
export const dynamic='force-dynamic';

const label=(kind:string)=>({style:'Style de réponse',knowledge:'Connaissance',policy:'Règle métier',customer_note:'Note client'} as Record<string,string>)[kind]||kind;

export default async function MemoirePage(){
 const [rows,stats,clients]=await Promise.all([listMemoryEntries(),memoryStats(),listCustomers()]);
 return <><div className="top"><div><h1>Mémoire commerciale</h1><div className="muted">Historique client, exemples de ton style et connaissances métier utilisées comme contexte par l’IA.</div></div><strong>{stats.active} actifs</strong></div>
 <section className="grid">{[['Style',stats.style],['Importés WhatsApp',stats.importedStyle],['Connaissances',stats.knowledge],['Total',stats.total]].map(([l,v])=><div className="card" key={l}><div className="muted">{l}</div><div className="value">{v}</div></div>)}</section>
 <section className="cols"><form className="card anchor-target" id="import-whatsapp" action={importWhatsAppHistoryAction}><h2>Importer un ancien chat WhatsApp</h2><p className="muted">Exporte une conversation WhatsApp sans médias, puis importe le fichier .txt. Le CRM conservera l’historique et extraira jusqu’à 60 exemples de tes réponses.</p><label>Numéro WhatsApp du client *</label><input name="clientPhone" required placeholder="+237 6XXXXXXXX"/><label>Nom du client</label><input name="clientName" placeholder="Ex. Kevin M."/><label>Ton nom tel qu’il apparaît dans l’export *</label><input name="ownNames" required placeholder="Ex. Tonny"/><p className="muted">Si plusieurs noms te représentent, sépare-les par des virgules.</p><label>Langue principale</label><select name="importLanguage" defaultValue="fr"><option value="fr">Français</option><option value="en">Anglais</option></select><label>Fichier .txt WhatsApp</label><input name="chatFile" type="file" accept=".txt,text/plain"/><label>Ou colle le texte de l’export</label><textarea name="chatText" rows={7} placeholder="25/09/2026, 10:30 - Client: Bonjour…"/><button type="submit">Analyser et importer</button><p className="muted">Importe uniquement des conversations commerciales que tu es autorisé à conserver dans ton CRM. Les doublons exacts sont bloqués automatiquement.</p></form>
 <div className="card"><h2>Ce que l’import fait</h2><div className="row"><span>Historique du chat</span><strong>Conservé</strong></div><div className="row"><span>Client reconnu par numéro</span><strong>Oui</strong></div><div className="row"><span>Tes réponses utiles</span><strong>Apprises comme exemples</strong></div><div className="row"><span>Prix et services</span><strong>Catalogue uniquement</strong></div><div className="row"><span>Paiement / activation</span><strong>Jamais déduits automatiquement</strong></div><div className="notice" style={{marginTop:14}}>Le système apprend surtout ta manière de répondre. Il ne transforme pas une ancienne phrase en prix actuel ou en preuve de paiement.</div></div></section>
 <section className="cols" style={{marginTop:16}}><form className="card" action={createMemoryAction}><h2>Ajouter une mémoire manuellement</h2><label>Type *</label><select name="kind" required defaultValue="style"><option value="style">Style de réponse</option><option value="knowledge">Connaissance métier</option><option value="policy">Règle métier</option><option value="customer_note">Note liée à un client</option></select><label>Titre</label><input name="title" placeholder="Ex. Réponse courte pour demander le prix"/><label>Langue</label><select name="language" defaultValue="fr"><option value="fr">Français</option><option value="en">Anglais</option></select><label>Client (seulement pour une note client)</label><select name="customerId" defaultValue=""><option value="">Aucun / global</option>{clients.map(c=><option key={c.id} value={c.id}>{[c.firstName,c.lastName].filter(Boolean).join(' ')||c.phone} — {c.phone}</option>)}</select><label>Contenu *</label><textarea name="content" rows={6} required placeholder="Colle ici un bon exemple de réponse, une règle commerciale ou une information utile."/><button type="submit">Enregistrer dans la mémoire</button></form>
 <div className="card"><h2>Comment l’IA l’utilise</h2><p>L’IA consulte les derniers messages du client, ses abonnements, les exemples de ton style et les connaissances pertinentes avant de répondre.</p><p className="muted">Les prix et disponibilités restent toujours lus depuis le catalogue actif. Une mémoire ne peut pas remplacer le catalogue comme source de vérité.</p><div className="notice">Les nouvelles conversations WhatsApp seront enregistrées automatiquement dès que le webhook Meta sera branché.</div></div></section>
 <div className="card" style={{marginTop:16}}><h2>Mémoires enregistrées</h2>{rows.length===0?<p className="muted">Aucune mémoire enregistrée pour le moment.</p>:rows.map(r=><div className="row" key={r.id}><span><strong>{r.title||label(r.kind)}</strong><br/><span className="muted">{label(r.kind)}{r.sourceType==='whatsapp_import'?' · Import WhatsApp':''}{r.customerId?` · ${[r.firstName,r.lastName].filter(Boolean).join(' ')||r.phone}`:' · Global'}</span><br/><span>{r.content.length>180?`${r.content.slice(0,180)}…`:r.content}</span></span><form action={toggleMemoryAction}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="active" value={String(!r.active)}/><button type="submit" className="secondary-button">{r.active?'Désactiver':'Activer'}</button></form></div>)}</div></>;
}
